#!/bin/bash

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PAYLOAD=$(mktemp /tmp/sonarqube-resource-in.XXXXXX)

cat > "${PAYLOAD}" <&0

#This output is simply used to have a no-ops in
jq -n "{
  version: { ce_task_id: \"empty\"},
  metadata: [
      { name: \"ce_task_status\", value: \"empty\" },
      { name: \"project_status\", value: \"empty\" }
  ]
}" >&3